progressions:
  "IIm7, V7, IMaj7": "major | IIm7, V7, IMaj7"
  "IMaj7, VIm7, IIm7, V7": "major | IMaj7, VIm7, IIm7, V7"
  "IMaj7, IVMaj7, V7, IMaj7": "major | IMaj7, IVMaj7, V7, IMaj7"
  "IMaj7, VIm7, IVMaj7, V7": "major | IMaj7, VIm7, IVMaj7, V7"
  "IIm7b5, V7b9, Im": "minor | IIm7b5, V7b9, Im"
  "bVIMaj7, bVII6, Im": "minor | bVIMaj7, bVII6, Im"
  "Im, bVII6, bVIMaj7, V7b9": "minor | Im, bVII6, bVIMaj7, V7b9"
  "Im, IVm7, V7b9": "minor | Im, IVm7, V7b9"
