progressions:
  - "IIm7, V7, IMaj7"
  - "IMaj7, VIm7, IIm7, V7"
  - "IMaj7, IVMaj7, V7, IMaj7"
  - "IMaj7, VIm7, IVMaj7, V7"
  - "IIm7b5, V7b9, Im"
  - "bVIMaj7, bVII6, Im"
  - "Im, bVII6, bVIMaj7, V7b9"
  - "IMaj7, V7, VIm7, IVMaj7"
  - "IIIm7, VIm7, IIm7, V7"
  - "IIm7, V7, IIIm7, VIm7"
  - "IMaj7, VI7, IIm7, V7"
  - "III7, VI7, II7, V7"
  - "IIm7, bII7, IMaj7"
  - "IVm7, bVII7, IMaj7"
  - "IVMaj7, IVm7, IMaj7"
  - "IMaj7, bVII6, IVMaj7, IMaj7"
  - "IMaj7, bVIMaj7, bVII6, IMaj7"
  - "Im, IVm7, V7b9, Im"
  - "Im, bVIMaj7, bIIIMaj7, bVII6"
  - "I7, IV7, I7, V7"
