progressions:
  "Major ii-V-I": "major | IIm7, V7, IMaj7"
  "Major I-vi-ii-V": "major | IMaj7, VIm7, IIm7, V7"
  "Major I-IV-V-I": "major | IMaj7, IVMaj7, V7, IMaj7"
  "Major I-vi-IV-V": "major | IMaj7, VIm7, IVMaj7, V7"
  "Minor ii-V-i": "minor | IIm7b5, V7b9, Im"
  "Minor bVI-bVII-i": "minor | bVIMaj7, bVII6, Im"
  "Minor i-bVII-bVI-V": "minor | Im, bVII6, bVIMaj7, V7b9"
  "Minor i-iv-V": "minor | Im, IVm7, V7b9"
